# <font color='black'>FS25 PROG MEP</font>
**5. Juli 2025**

## Informationen zur MEP
### Dauer: 
120 Min


### Total mögliche Punktzahl:
100 Punkte


### Erlaubte Hilfsmittel
Die Prüfung ist "Open Book", d.h. erlaubt sind folgende Mittel:
- Vorlesungsskript und gelöste Übungen
- Persönliche Zusammenfassung
- Dokumentation https://devdocs.io/ im **Offline Modus** zu: Python Standardbibliothek, NumPy, Pandas, Matplotlib Dokumentation 


### Nicht erlaubt sind:
- Anbindung ans Internet. Bitte schalten sie alle Netzwerkverbindung aus.
- Kommunikation mit Dritten während der Prüfung
- Bezug fremder Hilfe, oder Hilfe leisten (z.B. Ergebnisse teilen, Tipps geben, etc.)
- Keine elektronischen Geräte (NATEL, Kopfhörer, ...)
- Online-Internetrecherche
- Chat-bots, sowie jede andere, nicht explizit erlaubte Handlung


### Instruktionen
- Sie müssen die Aufgaben in diesem Jupyter Notebook direkt lösen. Fügen Sie die Lösung direkt unterhalb der Frage ein. 
- Teillösungen werden auch bewertet
- Gewisse Aufgaben verweisen möglicherweise auf Dateien, welche heruntergeladen und in Ihrem Arbeitsverzeichnis abgelegt werden müssen, damit alls korrekt ausgeführt werden kann. 

- Speichern Sie die Jupyter Prüfungsdatei mit Ihren Lösungen unter Verwendung folgender Namenskonvention: <font color="magenta">_**Nachname_Vorname_2025_07_05_final_exam.ipynb**_</font>
- Laden Sie ihre Lösung spätestens nach Abschluss der Prüfung in Ilias in den Abgabeordner hoch.
- Falls die Abgabe wider Erwarten über Ilias nicht möglich, melden Sie dies der Aufsicht und senden Sie die gelösten Aufgaben von Ihrer offiziellen HSLU-E-Mail-Adresse an <a href='mailto:bjoern.jensen@hslu.ch'>bjoern.jensen@hslu.ch</a>

<br>

<br>

## Redlichkeitsbedingungen
**Mit der Absolvierung der Prüfung bestätige ich, dass ich:**
- die Prüfungen alleine und ohne unerlaubte fremde Hilfe absolviert habe,
- die Lösungen und Resultate selbst hergeleitet habe,
- keine anderen als die für die entsprechende Prüfung ausdrücklich vorgesehenen Hilfsmittel benutzt habe,
- keine unerlaubte Kommunikation mit Dritten während der Prüfung geführt habe

Bei Unredlichkeiten gilt der Artikel 39 der Studienordnung für Ausbildung an der Hochschule Luzern, FH Zentralschweiz (Nr. 521).

&nbsp;

&nbsp;
<font color='magenta'>_**Datum, Name und Vorname**_</font>

05.07.25, Schlumpf Timo

# Aufgabe 1: Flowchart

<div style="text-align: right"> <font color="magenta"> [ ___ / 3 ] </div>

Setzen Sie das nachstehend gezeigte Flowchart in lauffähigen Python-Code um.

![Another SVG image](./img/flowchart.svg)

<font color='magenta'>_**Antwort**_</font>

In [4]:
# your code
try:
  x = int(input('Gebe einen gültigen Integer an.'))
  print(x)
except:
  print('Bitte gib einen gültigen Integer an.')

Bitte gib einen gültigen Integer an.

# Aufgabe 2: Namenskonventionen

## 2.1 Funktionsnamen

<div style="text-align: right"> <font color="magenta"> [ ___ / 7 ] <font color="black"> </div>
<div style="text-align: left"> <font color='purple'>
.
</font> </div>

Gegeben sind untenstehende Vorschläge für *Funktionsnamen*. 

Welche Vorschläge sind zulässig, welche nicht? 
Begründen sie Ablehnungen jeweils mit einem Satz.


+ `calculate_area`

+ `my-function` 
+ `print`

+ `display_results`

+ `1st` 
+ `check_for_errors`

+ `class`

+ `update_database`

<font color='magenta'>_**Antwort**_</font>

In [ ]:
"""
Nicht zulässig:
- 'my-function': Bindestrich
- 'print': reserviertes Keyword
- '1st': Zahlen sind nicht erlaubt im Funktionsnamen
- 'class': reserviertes Keyword

"""

## 2.2   Funktionsdefinition

<div style="text-align: right"> <font color="magenta"> [ ___  / 4 ] <font color="black"> </div>
<div style="text-align: left"> <font color='purple'>
.
</font> </div>

Gegeben sind folgende Vorschläge für *Funktionen*. 

Welche Vorschläge sind zulässig, welche nicht? 
Begründen sie Ablehnungen jeweils mit **mindestens** einem Satz und machen sie **einen** Vorschlag, wie eine richtige Definition aussehen würde.

> Es geht nur hier nur um die *Definition* der Funktion, also die erste mit `def` startende Zeile. Es ist **nicht** nach einer Implementierung gefragt.

def multiply_all(*pass):
    """
    computes and returns product of all elements
    """
    pass

def fib(n, cache={0:1, 1:1}):
    """
    computes the n-th Fibonacci number and returns it.
    """
    pass

def rect_surface(a=1, b):
    """
    computes and returns area of rectangle with side lengths of a and b.
    """
    pass

<font color='magenta'>_**Antwort**_</font>

**nicht zulässig:**
```python
def multiply_all(*pass):
  pass
```
- Bei 'pass' handelt es sich um ein reserviertes Keyword. Eine korrekte definition wäre:
```python
def multiply_all(*numbers):
  # ...
  pass
```

# Aufgabe 3: Schleifen und Comprehensions

Lösen sie die nachstehenden Teilaufgaben einmal ohne und einmal mit _comprehension_.

## 3.1 Wurzel-Liste

Berechnen Sie die Wurzel der Zahlen von 1 bis 9 und legen Sie das Ergebnis in einer Liste ab.

> Lösen Sie dies einmal ohne und einmal nur mit *list-comprehension*.

### 3.1.1 Ansatz ohne *list-comprehension*

<div style="text-align: right"> <font color="magenta"> [ ___ / 1 ] </div>

<font color='magenta'>_**Code**_</font>

In [ ]:
# your code
import math

out = []
for i in range(1,10):
  out.append(math.sqrt(i))

9

### 3.1.2 Ansatz mit *list-comprehension*

<div style="text-align: right"> <font color="magenta"> [ ___ / 1 ] </div>

<font color='magenta'>_**Code**_</font>

In [ ]:
# your code
out = [math.sqrt(i) for i in range(1,10)]

9

## 3.2 Transponierte Matrix

Aufgabe: Gegeben ist eine Matrix (repräsentiert als Liste von Listen). Transponiere diese Matrix mithilfe einer einzigen verschachtelten List Comprehension.

> Lösen Sie dies einmal ohne und einmal nur mit *list-comprehension*.

*Beispiel-Input:*

In [22]:
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

*Beispiel Output:*

In [8]:
matrix_T = [[1, 4, 7],
            [2, 5, 8],
            [3, 6, 9]]

### 3.2.1 Ansatz ohne *list-comprehension*

<div style="text-align: right"> <font color="magenta"> [ ___ / 2 ] </div>

<font color='magenta'>_**Code**_</font>

In [29]:
# your code
out = []
for x in range(0,len(matrix)):
  temp = []
  for y in range(0,len(matrix[x])):
    temp.append(matrix[y][x])
  out.append(temp)

out

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

### 3.2.2 Ansatz mit *list-comprehension*

<div style="text-align: right"> <font color="magenta"> [ ___ / 2 ] </div>

<font color='magenta'>_**Code**_</font>

In [ ]:
# your code
out = [[matrix[x][y] for x in range(0,len(matrix))] for y in range(0,len(matrix[x]))]
out

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

## 3.3 Erstellen von Tupeln mit Indices

Gegeben ist ein String. Erstelle eine Liste von Tupeln, wobei jedes Tupel das Zeichen und seinen Index im String enthält, aber nur für Vokale (a, e, i, o, u, Gross-/Kleinschreibung ignorieren).

> Lösen Sie dies einmal ohne und einmal nur mit *list-comprehension*.

*Beispiel-Input:*

In [36]:
text = "Hello Python"

*Beispiel-Output:*

In [14]:
[('e', 1), ('o', 4), ('o', 9)]

[('e', 1), ('o', 4), ('o', 9)]

### 3.3.1 Ansatz ohne *list-comprehension*

<div style="text-align: right"> <font color="magenta"> [ ___ / 2 ] </div>

<font color='magenta'>_**Antwort**_</font>

In [42]:
# your code
out = []
for i in range(0,len(text)):
  if text.lower()[i] in 'aeiou':
    out.append((text[i],i))
out

[('e', 1), ('o', 4), ('o', 10)]

### 3.3.2 Ansatz mit *list-comprehension*

<div style="text-align: right"> <font color="magenta"> [ ___ / 2 ] </div>

<font color='magenta'>_**Antwort**_</font>

In [41]:
# your code
out = [(text[i], i) for i in range(0,len(text)) if text.lower()[i] in 'aeiou']
out

[('e', 1), ('o', 4), ('o', 10)]

# 4 Erstellen eines Dictionaries aus zwei Listen

Gegeben sind zwei Listen: eine Liste von Schlüsseln und eine Liste von Werten. Erstelle ein Dictionary, das Paare von Schlüsseln und Werten enthält. Wenn ein Wert jedoch ein Vielfaches von 3 ist, soll stattdessen "MultiplesOfThree" als Wert eingetragen werden. Gehe davon aus, dass beide Listen die gleiche Länge haben.

> Lösen Sie dies einmal ohne und einmal nur mit **dict-comprehension**.

*Beispiel-Input:*

In [43]:
keys = ["a", "b", "c", "d", "e"]
values = [1, 6, 3, 8, 10]

*Beispiel-Output:*

In [20]:
result = {'a': 1, 'b': 'MultiplesOfThree', 'c': 'MultiplesOfThree', 'd': 8, 'e': 10}

### 4.1 Ansatz ohne *dict-comprehension*

<div style="text-align: right"> <font color="magenta"> [ ___ / 1 ] </div>

<font color='magenta'>_**Code**_</font>

In [46]:
# your code
out = dict()
for i in range(0,len(keys)):
  if values[i] % 3 == 0:
    out[keys[i]] = 'MultiplesOfThree'
  else:
    out[keys[i]] = values[i]
out

{'a': 1, 'b': 'MultiplesOfThree', 'c': 'MultiplesOfThree', 'd': 8, 'e': 10}

### 4.2 Variante nur mit *dict-comprehension*

<div style="text-align: right"> <font color="magenta"> [ ___ / 1 ] </div>

<font color='magenta'>_**Code**_</font>

In [49]:
# your code
out = {keys[i]: 'MultiplesOfThree' if values[i] % 3 == 0 else values[i] for i in range(0, len(keys))}
out

{'a': 1, 'b': 'MultiplesOfThree', 'c': 'MultiplesOfThree', 'd': 8, 'e': 10}

# Aufgabe 5: Textanalyse

Sie arbeiten als Linguist mit (kuzen) Textdokumenten und möchten den Gebrauch von Wörtern verstehen. In einem ersten Schritt sollen die untenstehende Textdaten aufbereitet, also vorverarbeitet werden. Im Anschluss werden gemeinsame und einzigartige Wörter identifiziert.

Beispieldaten:

In [50]:
sentences = [
    "The quick brown fox jumps over the lazy dog.",
    "A lazy cat sleeps in the sun.",
    "The quick dog runs after the ball.",
    "The sun rises in the east."
]

## 5.1 Vorverarbeitung

<div style="text-align: right"> <font color="magenta"> [ ___  / 4 ] <font color="black"> </div>
<div style="text-align: left"> <font color='purple'>
.
</font> </div>

Um den Text vorzuverarbeiten soll er mit Hilfe der Funktion `preprocess_text()` in Kleinbuchstaben gewandelt, von allen Satzzeichen befreit und in einzelne Wörter aufgeteilt werden. Die Funktion gibt für jede Zeichenketten eine Liste von Wörtern zurück. Stellen Sie sicher, dass diese Liste jedes Wort nur einmal enthält.

> Kleinbuchstaben sind bspw. im `string`-Modul gegeben: `string.ascii_lowercase`.

<font color='magenta'>_**Antwort**_</font>

In [56]:
# your solution
import string
def preprocess_text(txt):
  out = []
  for row in txt:
    row = row.lower()
    for c in row:
      if c in string.punctuation:
        row = row.replace(c, '')
    out.append(row.split(' '))
  return out

preprocess_text(sentences)

[['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog'],
 ['a', 'lazy', 'cat', 'sleeps', 'in', 'the', 'sun'],
 ['the', 'quick', 'dog', 'runs', 'after', 'the', 'ball'],
 ['the', 'sun', 'rises', 'in', 'the', 'east']]

## 5.2 Analyse

<div style="text-align: right"> <font color="magenta"> [ ___  / 6 ] <font color="black"> </div>
<div style="text-align: left"> <font color='purple'>
.
</font> </div>

Die Analyse schliesst sich an die Datenaufbereitung `preprocess_text()` an. Als Hilfe wird hier ein Zwischenresultat `preprocessed_sentences` angegeben, das im Folgenden verwendet werden kann.

In [57]:
preprocessed_sentences = [
    ['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog'],
    ['a', 'lazy', 'cat', 'sleeps', 'in', 'the', 'sun'],
    ['the', 'quick', 'dog', 'runs', 'after', 'the', 'ball'],
    ['the', 'sun', 'rises', 'in', 'the', 'east']]

### 5.2.1 Einzigartige Worte

<div style="text-align: right"> <font color="magenta"> [ ___  / 2 ] <font color="black"> </div>
<div style="text-align: left"> <font color='purple'>
.
</font> </div>

Erstellen Sie eine Liste der Worte, aus denen die oben stehenden Satzliste (`sentences`) zusammengesetzt werden könnte.
In der Ergebnisliste soll jedes Wort nur einmal vorkommen.

> Sie können dabei die Liste `preprocessed_sentences` verwenden, oder die Funktion `preprocess_text()` zur Vorverarbeitung aufrufen.

<font color='magenta'>_**Antwort**_</font>

In [ ]:
# your code
unique_wlist = list(set([word for row in preprocessed_sentences for word in row]))
unique_wlist

### 5.2.2 Satzspezifische Worte

<div style="text-align: right"> <font color="magenta"> [ ___  / 4 ] <font color="black"> </div>
<div style="text-align: left"> <font color='purple'>
.
</font> </div>

Erstellen Sie eine Liste aus Worten, die nur in einem der Sätze, aus der oben stehenden Satzliste (`sentences`) vorkommen.
In der Ergebnisliste soll jedes Worte nur einmal vorkommen.

> Sie können dabei die Liste `preprocessed_sentences` verwenden, oder die Funktion `preprocess_text()` zur Vorverarbeitung aufrufen.

<font color='magenta'>_**Antwort**_</font>

In [75]:
# reassigned for less typing
prep_sen = preprocessed_sentences

unique_words = []
for y in range(0,len(prep_sen)):
  for word in prep_sen[y]:
    if [w for n in range(0,len(prep_sen)) for w in prep_sen[n]].count(word) == 1:
      unique_words.append(word)

unique_words

['brown',
 'fox',
 'jumps',
 'over',
 'a',
 'cat',
 'sleeps',
 'runs',
 'after',
 'ball',
 'rises',
 'east']

# Aufgabe 6: Exception-Handling

<div style="text-align: right"> <font color="magenta"> [ ___ / 4 ] <font color="black"> </div>
<div style="text-align: left"> <font color='purple'>
.
</font> </div>

Passen Sie das unten stehende Python-Program so an, das:
+ Exceptions, die sich aus der Benutzereingaben ergeben abgefangen werden und solange wieder zur Eingabe des Wertes führen, bis ein korrekter Integer-Wert eingelesen wurde.
+ wenn die Differenz 'd' negativ wird, soll ein `ValueError` erzeugt werden.

v1 = int(input('First integer value? '))
v2 = int(input('Second integer value? '))
d = v1 - v2
print(d)

<font color='magenta'>_**Antwort**_</font>

In [77]:
# your code

def get_input():
  try:
    v1 = int(input('First integer value? '))
    v2 = int(input('Second integer value? '))
    return [v1, v2]
  except:
    get_input()

vars = get_input()
d = vars[0] - vars[1]
if d < 0:
  ValueError('result cant be negative.')
else:
  print(d)

0

# Aufgabe 7: Kreditkartennummern prüfen

<div style="text-align: right"> <font color="magenta"> [ ___ / 9 ] <font color="black"> </div>
<div style="text-align: left"> <font color='purple'>
.
</font> </div>

Kreditkartennummern bestehen aus einer Reihe von Ziffern, die mit einer Prüfziffer endet. Das ermöglicht Tippfehler bei der Eingabe schnell zu erkennen und so die Korrektheit der Kreditkartennummer zu überprüfen. Die Prüfziffer ist immer die letzte Ziffer der Kreditkartennummer.

Die Prüfsumme kann aus der Kreditkartennummer wie folgt berechnet werden:

+ Die Kreditkartennummer wird aufgespalten: in die reine Kreditkartennummer und separat
die letzte Zahl als Prüfziffer.

+ Beginnend mit der letzten Ziffer, also vom rechten Ende der reinen Kreditkartennummer wird jede zweite Ziffer verdoppelt, also mit 2 multipliziert.
+ Ergibt sich bei der Verdopplung als Ergebnis ein ein zweistelliger Wert, dann werden werden beide Ziffern einfach miteinander addiert.
+ Abschliessend werden alle Werte in einer Summe $s$ zusammengefasst.
  
+ Aus der Summe $s$ ergibt sich die Prüfziffer wie folgt: $10 – ( s~\textrm{modulo}~10 )$.

*Beispiel:*

Wir nehmen an die Kreditkartennummer sei 79927398713. 
Also ist die Prüfziffer 3, da es die letzte Ziffer der Kreditkartennummer ist.
Die reine Kreditkartennummer ist 7992739871, dass ist die zu verarbeitende Zahl.

+ Die Summe $s$ ergibt sich aus dem oben beschriebenen Vorgehen zu 67.

+ Die Prüfziffer ergibt sich aus der Summe $s$ wie folgt: 10 – ( *67* mod 10 ) = 3

+ Da die Prüfziffer 3 der letzten Ziffer der Kreditkartennummer entspricht ist die Kreditkartennummer korrekt.

*Beispiele von korrekten und inkorrekten Kreditkartennummern für allfällige Tests.*

ccn_ok = {
    'visa': '4242 4242 4242 4242',
    'mastercard': '5454 5454 5454 5454', 
    'amex': '3782 8224 6310 005',
    'tester': '79927398713'
}

ccn_fails = {
    'fail_one': '6510 0000 0000 0002',
    'fail_two': '3528 2000 0000 0000'

}

### Ihre Aufgabe
Schreiben Sie eine Funktion `checksum_credit_card_number(ccn)`, die eine Kreditkartennummer (`ccn`) als String-Argument nimmt und die Prüfziffer berechnet und als String zurückgibt.

> Es ist nach der *Berechnung* gefragt. Die einfache Rückgabe der letzten Ziffer genügt nicht!

<font color='magenta'>_**Antwort**_</font>

In [197]:
# Something is not quite right with the sum part - didn't have time to fix!
def checksum_credit_card_number(ccn):
  ccn = [int(c) for c in ccn]
  for i in reversed(range(0, len(ccn)-1,2)):
    dbl = int(ccn[i]) * 2
    ccn[i] = sum([int(c) for c in str(dbl)])
  return 10 - (sum(ccn) % 10)
checksum_credit_card_number('79927398713')

1

## Aufgabe 8 – NumPy: Array-Berechnungen (10 Punkte)

Gegeben sei ein NumPy-Array mit zufälligen Zahlen. Schreiben Sie eine Funktion, die folgende Schritte ausführt:

Hinweis: 
Ein Z-Wert gibt an, wie viele Standardabweichungen ein Datenpunkt vom Mittelwert entfernt ist.  
Er wird berechnet durch:

$z = \frac{x - \mu}{\sigma}$

Dabei ist $x$ der Wert, $\mu$ der Mittelwert und $\sigma$ die Standardabweichung.  
Z-Werte standardisieren Daten und machen sie vergleichbar.

In [ ]:
import numpy as np

def analyse_array(arr):
    # TODO: Mittelwert berechnen
    mean = np.mean(arr)

    # TODO: Standardabweichung berechnen
    std = np.std(arr)

    # TODO: Array normalisieren (Z-Werte)
    z_scores = [((x - mean) / std) for x in arr]

    return z_scores

# Testen mit Zufallsarray
array = np.random.normal(10, 2, 100)
analyse_array(array)

## Aufgabe 9 – Pandas: Daten analysieren (10 Punkte)
Gegeben ist ein DataFrame mit Verkaufsdaten:

In [122]:
import pandas as pd

data = {
    "Produkt": ["A", "B", "A", "C", "B", "C", "A"],
    "Umsatz": [100, 200, 150, 300, 220, 330, 180],
    "Region": ["Nord", "Süd", "Nord", "West", "Süd", "West", "Nord"]
}
df = pd.DataFrame(data)
df

  Produkt  Umsatz Region
0       A     100   Nord
1       B     200    Süd
2       A     150   Nord
3       C     300   West
4       B     220    Süd
5       C     330   West
6       A     180   Nord

Aufgaben:

1. Durchschnittlicher Umsatz pro Produkt (4 Punkte)
2. Zeilen mit Umsatz > 200 filtern (2 Punkte)
3. Summe des Umsatzes pro Region berechnen (4 Punkte)

In [160]:
# TODO: Durchschnittlicher Umsatz pro Produkt
df.groupby('Produkt')['Umsatz'].median()
# TODO: Filter auf Umsatz > 200
df.where(df['Umsatz'] > 200)
# TODO: Gruppierung nach Region und Summierung
df.sort_values(by='Region')

  Produkt  Umsatz Region
0       A     100   Nord
2       A     150   Nord
6       A     180   Nord
1       B     200    Süd
4       B     220    Süd
3       C     300   West
5       C     330   West

## Aufgabe 10 – Objektorientierte Programmierung (10 Punkte)

Implementieren Sie eine Klasse Rechteck, die zwei Attribute breite und höhe hat. Die Klasse soll:

1. Ein __init__-Konstruktor haben (2 Punkte)

2. Eine Methode flaeche() zur Berechnung der Fläche implementieren (2 Punkte)

3. Eine Methode ist_quadrat() zurückgeben, ob es sich um ein Quadrat handelt (2 Punkte)

4. Die __str__() Methode überschreiben, um ein lesbares Format zu geben, z. B. "Rechteck(5 x 10)" (2 Punkte)

5. Ein Klassenattribut anzahl_objekte, das zählt, wie viele Rechtecke erzeugt wurden (2 Punkte)

In [184]:
class Rechteck:
  breite = 0
  hoehe = 0
  anzahl_objekte = 0
  def __init__(self, breite, hoehe):
    self.breite = breite
    self.hoehe = hoehe
    Rechteck.anzahl_objekte += 1

  def flaeche(self):
    return self.breite * self.hoehe

  def ist_quadrat(self):
    return self.breite == self.hoehe

  def __str__(self):
    return f"Rechteck({self.breite} x {self.hoehe})"

## Aufgabe 11 – Web-Scraping mit `requests` und `BeautifulSoup` (10 Punkte)

Sie möchten von der Website https://quotes.toscrape.com alle Zitate der Startseite extrahieren.

1. Senden Sie eine GET-Anfrage an die Seite. (2 Punkte)

2. Parsen Sie den HTML-Inhalt mit BeautifulSoup. (2 Punkte)

3. Extrahieren Sie alle Zitate (Tags mit Klasse "text", `<span class="text">`). (3 Punkte)

4. Speichern Sie die Zitate in einer Liste. (3 Punkte)

![Screenshot of website quotes.toscrape.com](./img/prog_webscr.png)

In [ ]:
import requests
from bs4 import BeautifulSoup

url = "https://quotes.toscrape.com"
response = requests.get(url)

soup = BeautifulSoup.decode(response)

quotes = []
for quote_tag in soup.find_all("span", class_="text"):
  quotes.append(quote_tag.innerText)

## Aufgabe 12 – API-Zugriff mit `requests` (10 Punkte)
Verwenden Sie die API `https://api.agify.io`, um das geschätzte Alter für einen Namen abzurufen.

1. Funktion `get_age(name)` schreiben (3 Punkte)
2. `requests.get` mit Parametern verwenden (3 Punkte)
3. Alter aus JSON extrahieren (2 Punkte)
4. Funktion auf mehrere Namen anwenden (2 Punkte)

![Screenshot of api.agify.io](./img/prog_api.png)

In [ ]:
import requests

def get_age(name):
    url = "https://api.agify.io"
    params = {
        "name": name
    }
    response = requests.get(url=url,params=params)
    data = response.json()
    age = data['age']
    return age

# Beispiele
names = ["Anna", "Liam", "Mia"]
for name in names:
    print(name, ":", get_age(name))